import { useTheme } from "@/app/theme";
import { OverrideToken } from "antd/es/theme/interface";
import { useMemo } from "react";

export const useOverride = () => {
  const {
    theme: { colors },
  } = useTheme();
  const Override: OverrideToken = useMemo(() => {
    return {
      Button: {
        borderRadius: 8,
        borderRadiusSm: 8,
        colorBgBase: colors.buttons.default.defBut,
        fontSize: 14,
        contentFontSizeSM: 14,
        controlHeight: 40,
        controlHeightSM: 48,
        lineHeight: 20,
        paddingContentHorizontal: 12,
        colorBorder: colors.buttons.default.strokeButDef,
        // colorBgContainer: colors.gray[100],
        colorText: colors.buttons.primary.priBut,
        colorBgContainerDisabled: colors.buttons.primary.priDisBut,
        colorTextDisabled: colors.buttons.primary.tButDisPri,
        primaryColor: colors.buttons.whiteText.tWhiteBut,
        colorPrimaryBg: colors.buttons.primary.priBut,
        colorPrimaryActive: colors.buttons.primary.priBut,
        colorPrimary: colors.buttons.primary.priBut,
        colorPrimaryBorder: colors.buttons.primary.strokeButPri,
        colorPrimaryHover: colors.buttons.primary.priDisBut,
        colorError: colors.buttons.danger.danBut,
        borderColorDisabled: colors.buttons.primary.priDisBut,
        colorBgContainer: "transparent",
        // colorBgContainer: colors.background.baseBg,
        controlOutline: "transparent",
        textHoverBg: colors.background.baseBg,
        defaultGhostColor: colors.buttons.primary.tButPri,
        ghostBg: "transparent",
        // ghostBg: colors.background.baseBg,
        defaultActiveBg: colors.buttons.default.defBut,
        defaultActiveBorderColor: colors.buttons.default.defBut,
        defaultActiveColor: colors.buttons.default.tButDef1,
        defaultBg: colors.buttons.default.defBut,
        defaultBorderColor: colors.buttons.default.defBut,
        defaultColor: colors.buttons.default.tButDef1,
        defaultHoverBg: colors.base.gray[200],
        defaultHoverBorderColor: colors.base.gray[200],
        defaultHoverColor: colors.buttons.default.tButDef1,
        defaultGhostBorderColor: colors.buttons.default.strokeButDef,
        textTextColor: colors.buttons.default.tButDef2,
        paddingInline: 12,
        paddingBlock: 0,
        boxShadow: "unset",
        boxShadowTertiary: "unset",
        boxShadowSecondary: "unset",
        textTextHoverColor: colors.buttons.default.tButDisDef,
        green5: colors.buttons.success.sucDisBut,
        green6: colors.buttons.success.sucBut,
        green7: colors.base.success[700],
        green1: colors.base.success[100],
        green2: colors.base.success[200],
        green3: colors.base.success[300],
        green4: colors.base.success[400],
      },
      Input: {
        colorBgBase: colors.inputs.bg.emptyBG,
        colorPrimaryBg: colors.inputs.bg.emptyBG,
        colorBorderBg: colors.inputs.bg.emptyBG,
        colorBgContainer: colors.inputs.bg.emptyBG,
        colorBorder: colors.inputs.stroke.border,
        lineWidth: 2,
        hoverBorderColor: colors.border.bor5,
        activeBorderColor: colors.border.bor4,
        fontSize: 14,
        borderRadius: 12,
        borderRadiusSm: 12,
        controlHeight: 40,
        controlHeightSM: 48,
        colorBgContainerDisabled: colors.inputs.bg.dontEditBG,
        colorTextPlaceholder: colors.inputs.text.emptyTx,
        colorText: colors.inputs.text.filedTx,
        colorTextDisabled: colors.inputs.text.dontEditTx,
        colorTextDescription: colors.inputs.text.titleTx,
        colorIcon: colors.icon.icDefInput,
        colorIconHover: colors.icon.icDefInput,
      },
      InputNumber: {
        colorBgBase: colors.inputs.bg.emptyBG,
        colorPrimaryBg: colors.inputs.bg.emptyBG,
        colorBorderBg: colors.inputs.bg.emptyBG,
        colorBgContainer: colors.inputs.bg.emptyBG,
        colorBorder: colors.inputs.stroke.border,
        lineWidth: 2,
        hoverBorderColor: colors.border.bor5,
        activeBorderColor: colors.border.bor4,
        fontSize: 14,
        borderRadius: 12,
        borderRadiusSm: 12,
        controlHeight: 40,
        controlHeightSM: 48,
        colorBgContainerDisabled: colors.inputs.bg.dontEditBG,
        colorTextPlaceholder: colors.inputs.text.emptyTx,
        colorText: colors.inputs.text.filedTx,
        colorTextDisabled: colors.inputs.text.dontEditTx,
        colorIcon: colors.icon.icDefInput,
        colorIconHover: colors.icon.icDefInput,
      },
      Select: {
        colorBgBase: colors.inputs.bg.filedBG,
        colorPrimaryBg: colors.inputs.bg.filedBG,
        colorBorderBg: colors.inputs.bg.filedBG,
        colorBgContainer: colors.inputs.bg.filedBG,
        colorBorder: colors.inputs.stroke.border,
        lineWidth: 2,
        hoverBorderColor: colors.border.bor5,
        activeBorderColor: colors.border.bor4,
        fontSize: 14,
        borderRadius: 12,
        borderRadiusSm: 12,
        controlHeight: 40,
        controlHeightSM: 48,
        colorBgContainerDisabled: colors.inputs.bg.dontEditBG,
        colorTextPlaceholder: colors.inputs.text.emptyTx,
        colorText: colors.inputs.text.filedTx,
        colorTextDisabled: colors.inputs.text.dontEditTx,
        colorBgElevated: colors.dropdownList.baseBG,
        fontWeight: 400,
        optionActiveBg: colors.dropdownList.DDBoxHovered,
        optionSelectedBg: colors.dropdownList.DDSelectedBg,

        colorIcon: colors.icon.icDefInput,
        colorIconHover: colors.icon.icDefInput,
        colorTextQuaternary: colors.icon.icDefInput,
        optionFontSize: 12,
      },
      DatePicker: {
        colorBgBase: colors.inputs.bg.emptyBG,
        colorPrimaryBg: colors.inputs.bg.emptyBG,
        colorBorderBg: colors.inputs.bg.emptyBG,
        colorBgContainer: colors.inputs.bg.emptyBG,
        colorBorder: colors.inputs.stroke.border,
        lineWidth: 2,
        hoverBorderColor: colors.border.bor5,
        activeBorderColor: colors.border.bor4,
        fontSize: 14,
        borderRadius: 12,
        borderRadiusSm: 12,
        controlHeight: 40,
        colorBgContainerDisabled: colors.inputs.bg.dontEditBG,
        colorTextPlaceholder: colors.inputs.text.emptyTx,
        colorText: colors.text.primaryText,
        colorTextDisabled: colors.text.thirdText,
        activeBg: colors.inputs.bg.emptyBG,
        cellHoverBg: colors.background.selectedBg,
        colorIcon: colors.icon.icDefInput,
        colorIconHover: colors.icon.icDefInput,
        hoverBg: colors.inputs.bg.emptyBG,
        colorBgElevated: colors.background.bg3,
        colorTextHeading: colors.text.primaryText,
        multipleSelectorBgDisabled: colors.text.thirdText,
        colorLink: colors.text.linkText,
        colorLinkHover: colors.text.selectedText,
        fontWeight: 400,
      },
      Radio: {
        colorBgContainerDisabled: colors.background.baseBg,
        colorBgContainer: colors.background.baseBg,
        colorBorder: colors.icon.icDefInput,
        colorPrimary: colors.icon.icPri,
        colorPrimaryHover: colors.text.whiteText,
        buttonBg: colors.background.baseBg,
        buttonCheckedBg: colors.buttons.primary.priBut,
        colorText: colors.text.primaryText,
        dotSize: 8,
        dotColorDisabled: colors.icon.icDisable,
        colorTextDisabled: colors.icon.icDisable,
        buttonCheckedBgDisabled: colors.icon.icDisable,
        radioSize: 14,
        radioColor: colors.buttons.primary.priBut,
        radioBgColor: colors.text.whiteText,
      },
      Form: {
        labelColor: colors.inputs.text.titleTx,
        labelHeight: 24,
      },
      Checkbox: {
        colorBgContainerDisabled: colors.background.baseBg,
        colorBgContainer: colors.background.baseBg,
        colorBorder: colors.icon.icDefInput,
        colorPrimary: colors.icon.icPri,
        colorPrimaryHover: colors.buttons.primary.priDisBut,
        buttonBg: colors.background.baseBg,
        buttonCheckedBg: colors.buttons.primary.priBut,
        colorText: colors.text.primaryText,
        colorTextDisabled: colors.disable.disable4,
      },

      Modal: {
        colorBgMask: colors.background.transparent,
        titleColor: colors.text.primaryText,
        titleFontSize: 18,
        headerBg: colors.background.headerBg,
        borderRadius: 12,
        borderRadiusLg: 12,
        borderRadiusSM: 12,
        contentPadding: 0,
        footerBg: colors.background.headerBg,
        footerPadding: 16,
        footerBorderRadius: "0 0 12px 12px",
        headerPadding: "12px 16px",
      },
      Tabs: {
        itemActiveColor: colors.border.borSelected,
        itemSelectedColor: colors.text.selectedText,
        itemHoverColor: colors.border.borHovered,
        itemColor: colors.disable.disable2,
        titleFontSize: 16,
        horizontalItemPadding: "8px",
        horizontalItemGutter: 16,
        inkBarColor: colors.border.borSelected,
        colorBorderSecondary: colors.background.baseBg,
        horizontalMargin: "0",
      },
      Table: {
        colorBgContainer: colors.table.bg.rowWhite,
        colorText: colors.table.text.cellTXT,
        colorTextHeading: colors.table.text.headerTXT,
        headerBg: colors.table.bg.headerDef,
        headerSplitColor: colors.table.bg.headerDef,
        headerColor: colors.table.text.headerTXT,
        cellPaddingInlineMD: 14.5,
        cellPaddingInlineSM: 14.5,
        cellPaddingBlockMD: 14.5,
        cellPaddingBlockSM: 14.5,
        stickyScrollBarBg: colors.disable.disable1,
        stickyScrollBarBorderRadius: 12,
        rowHoverBg: colors.background.hoverBg,
        lineWidth: 0,
        colorLinkActive: "red",
        fontSize: 12,
        fontSizeSM: 12,
        borderRadius: 8,
        headerBorderRadius: 8,
      },
      Pagination: {
        itemActiveBg: "transparent",
        fontSize: 12,
        borderRadius: 8,
        borderRadiusSM: 8,
        colorPrimary: colors.icon.icPri,
      },
      Divider: {
        //   colorSplit: colors.border2,
        //   marginLG: 12,
      },
      Dropdown: {
        colorBgElevated: colors.dropdownList.baseBG,
        controlItemBgHover: colors.background.hoverBg,
      },
      Collapse: {
        colorTextHeading: colors.sidebar.text.tSb1,
        fontSizeHeading1: 16,
        borderRadiusLG: 4,
        headerPadding: "8px 12px",
        headerBg: "transparent",
        colorBorder: "transparent",
        lineWidth: 0,
      },
    };
  }, [colors]);

  return Override;
};
